### ISSUE TITLE
Unable to Integrate this SDK For iOS9

### ISSUE THREAD

**Issue by kayasiri** [pinterest/ios-pdk#2]
Hi,

I have downloaded your SDK and trying to integrate for iOS9, but unfortunately it's not working. I got build errors also while I build that in Xcode 7.0 Beta and I am able to resolve them. So please help me on this so that I will integrate this SDK in my iOS App.

Thanks,
Kayasiri.

**Comment by rcancro** [comment]
Hi Kayasiri,

Sorry to hear you are having problems. I just tried building the example app using Xcode beta 6 and it worked (I did need to delete the Podfile.lock to get pod install to work -- that will be fixed in the repo shortly).

What beta version of Xcode are you using? What are the errors you are seeing? 

Thanks!
Ricky

**Comment by kayasiri** [comment]
Hi Ricky,

Thank you for responding. I am using Xcode Beta 7.0 and trying to install the app on iPad2 with iOS9.

I will delete Podfile.lock once and will try. 

If possible can you suggest me on how to run Example app in Xcode Beta 7.0 and please tell me the steps.

Thanks,
Kayasiri.
