### ISSUE TITLE
@import AFNetworking error via cocoapods when used in a swift project

### ISSUE THREAD

**Issue by tharindu** [pinterest/ios-pdk#23]
If we try to add PinterestSDK via Cocoapods to a project with ObjC and Swift. After Pod Update cannot build the project unless we change `@import AFNetworking;` in `PDKClient.h` to `#import <AFNetworking/AFNetworking.h>`. module AFNetworking not found error is shown otherwise with `@import AFNetworking;`
May be good to change it if possible.

**Comment by rcancro** [comment]
I recently merged a pull request that made this change. Please update your podfile to point to the latest commit of the SDK.

**Comment by antrix1989** [comment]
@import loads modules. I assume that @tharindu doesn't build pods as modules ("use_frameworks!" key in Podfile), so that is why he sees that error. I agree, that
```
 @import AFNetworking;
```
 should be replaced with 
```
#import <AFNetworking/AFNetworking.h>
```
so it will work for both cases. [You don't actually need to use the @import keyword. If you opt-in to using modules, all #import and #include directives are mapped to use @import automatically.](http://stackoverflow.com/questions/18947516/import-vs-import-ios-7)

**Comment by tharindu** [comment]
Great. Thanks :-)
